openapi: 3.0.4
info:
  title: Place autocomplete API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /autocomplete:
    get:
      summary: Returns a list of predict Place.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - in: query
          name: q
          description: search predict by placename.
          schema:
            type: string
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string